#!/usr/bin/env node
/**
 * Keeps `src/version.ts` in step with `package.json`.
 *
 * The SDK version is reported to the backend on every request
 * (`X-QuickAuth-SDK-Version`), which means it has to exist as a JavaScript
 * value — and `package.json` cannot be imported from `src/` without landing
 * outside `rootDir` and breaking `tsc`'s declaration output. So it is
 * generated here instead of typed twice.
 *
 * There is exactly one place a human edits the version: `package.json`
 * (usually via `npm version`, which the publish workflow runs). Everything
 * else derives from it:
 *
 *   - `src/version.ts`      — written by this script (`npm run build` → prebuild)
 *   - `android/build.gradle`— reads package.json directly via JsonSlurper
 *   - `ios/QuickAuthRnSdk.podspec` — reads package.json directly
 *
 * Usage:
 *   node scripts/sync-version.js           # write src/version.ts
 *   node scripts/sync-version.js --check    # exit 1 if it is out of date
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkgPath = path.join(root, 'package.json');
const outPath = path.join(root, 'src', 'version.ts');

const { version } = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
if (typeof version !== 'string' || !version) {
  console.error('[sync-version] package.json has no version');
  process.exit(1);
}

const contents = `/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Written by scripts/sync-version.js from package.json's "version" field,
 * which is the single source of truth for the SDK version. Regenerated by
 * \`npm run build\` (prebuild) and verified by \`npm test\` (pretest).
 *
 * Edit package.json (or run \`npm version\`) instead.
 */

/** SDK version reported in the \`X-QuickAuth-SDK-Version\` request header. */
export const SDK_VERSION = '${version}';

/** Platform tag reported in the \`X-QuickAuth-SDK\` request header. */
export const SDK_PLATFORM = 'react-native';
`;

const check = process.argv.includes('--check');
const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;

if (existing === contents) {
  if (!check) console.log(`[sync-version] src/version.ts already at ${version}`);
  process.exit(0);
}

if (check) {
  console.error(
    `[sync-version] src/version.ts is out of date (package.json is ${version}).\n` +
      '                Run: npm run version:sync'
  );
  process.exit(1);
}

fs.writeFileSync(outPath, contents, 'utf8');
console.log(`[sync-version] wrote src/version.ts (${version})`);
