/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Written by scripts/sync-version.js from package.json's "version" field,
 * which is the single source of truth for the SDK version. Regenerated by
 * `npm run build` (prebuild) and verified by `npm test` (pretest).
 *
 * Edit package.json (or run `npm version`) instead.
 */

/** SDK version reported in the `X-QuickAuth-SDK-Version` request header. */
export const SDK_VERSION = '1.1.0';

/** Platform tag reported in the `X-QuickAuth-SDK` request header. */
export const SDK_PLATFORM = 'react-native';
